#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
    path: /
    controller: App\Controllers\Web\DefaultController::index
    defaults:
        template: base.html.twig